### ISSUE TITLE
Publish a release of this library on npm

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/flocking-midi-router#7]
We should publish a release of flocking-midi-router on the npm registry. This will make installation and usage much easier, as discussed in #5.

The only question: should we publish a dev release, or go ahead and publish this as a proper release of version <code>0.1.0</code>? My inclination is the latter; what do you think, @the-t-in-rtf?

**Comment by the-t-in-rtf** [comment]
Hi, @colinbdclark.  If there are no other blockers waiting to be merged, then yes, a full release makes good sense.  `0.1.0` is the default generated by `npm init`, IMO you deserve to publish `1.0.0` at this point.

**Comment by colinbdclark** [comment]
I've never used <code>npm init</code> before. I chose <code>0.1.0</code> because I thought it was profoundly reflective of the state of the system when I whipped it up.

<code>1.0.0.</code> it is. Bring on <code>2.0.0</code>!

**Comment by colinbdclark** [comment]
Published! https://www.npmjs.com/package/flocking-midi-router
